In [2]:
!pip install scikit-learn


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\Abhya Thakur\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip


In [5]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Models
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [3]:
!pip install pandas numpy matplotlib seaborn scikit-learn


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\Abhya Thakur\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip


In [6]:
train = pd.read_csv("train_KNN.csv")
test = pd.read_csv("test_KNN.csv")

train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [8]:
train['Age'] = train['Age'].fillna(train['Age'].median())
train['Embarked'] = train['Embarked'].fillna(train['Embarked'].mode()[0])

In [9]:
le = LabelEncoder()

train['Sex'] = le.fit_transform(train['Sex'])
train['Embarked'] = le.fit_transform(train['Embarked'])

In [10]:
train.drop(columns=['Name', 'Ticket', 'PassengerId'], inplace=True)

In [11]:
X = train.drop('Survived', axis=1)
y = train['Survived']

In [12]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_val)

print("KNN Accuracy:", accuracy_score(y_val, y_pred_knn))

KNN Accuracy: 0.7206703910614525


In [14]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_val)

print("Logistic Regression Accuracy:", accuracy_score(y_val, y_pred_lr))

Logistic Regression Accuracy: 0.8100558659217877


In [15]:
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_val)

print("Decision Tree Accuracy:", accuracy_score(y_val, y_pred_dt))

Decision Tree Accuracy: 0.7821229050279329


In [16]:
print("\n--- Model Comparison ---")
print("KNN Accuracy:", accuracy_score(y_val, y_pred_knn))
print("Logistic Regression Accuracy:", accuracy_score(y_val, y_pred_lr))
print("Decision Tree Accuracy:", accuracy_score(y_val, y_pred_dt))


--- Model Comparison ---
KNN Accuracy: 0.7206703910614525
Logistic Regression Accuracy: 0.8100558659217877
Decision Tree Accuracy: 0.7821229050279329


In [17]:
print("\nKNN Confusion Matrix:\n", confusion_matrix(y_val, y_pred_knn))
print("\nLogistic Regression Confusion Matrix:\n", confusion_matrix(y_val, y_pred_lr))
print("\nDecision Tree Confusion Matrix:\n", confusion_matrix(y_val, y_pred_dt))


KNN Confusion Matrix:
 [[89 16]
 [34 40]]

Logistic Regression Confusion Matrix:
 [[90 15]
 [19 55]]

Decision Tree Confusion Matrix:
 [[83 22]
 [17 57]]


In [ ]:
Observations:
KNN Model performs based on distance between data points but may be sensitive to scaling and choice of K.
Logistic Regression gives stable and interpretable results and works well for binary classification problems like survival prediction.
Decision Tree captures complex patterns but may overfit if not controlled.